apiVersion: v1
kind: Service
metadata:
  name: hppl
  labels:
    app: hppl
spec:
  type: ClusterIP
  selector:
    app: hppl
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.containerPort }}
